Backend/Controllers/AdminController.cs
using BP_AttendanceSystem_Lepine.Helpers;
using BP_AttendanceSystem_Lepine.Models;
using BP_AttendanceSystem_Lepine.Models.Db;
using BP_AttendanceSystem_Lepine.Models.DtoIn;
using BP_AttendanceSystem_Lepine.Models.DtoOut;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using NuGet.Packaging.Signing;

namespace BP_AttendanceSystem_Lepine.Controllers {

    [Route("/Admin")]
    [AdminAuthorize]
    public class AdminController : Controller {
        private readonly ILogger<AdminController> _logger;
        private GlobalContext _globalContext;
        public AdminController(ILogger<AdminController> logger, GlobalContext gc) {
            _logger = logger;
            _globalContext = gc;
        }
        [HttpGet]
        public IActionResult Index() {
            return View();
        }
        #region Employees
        [HttpGet]
        [Route("Employee/Shifts/{id}")]
        public async Task<IActionResult> EmployeeShifts(int id = 0, DateTime from = default, DateTime to = default) {
            if (from == default || to == default) {
                from = DateTime.Now.AddMonths(-1);
                to = DateTime.Now;
            }
            IEnumerable<Shift> shifts = await _globalContext.Shifts
                .Include(s => s.User)
                .Include(s => s.ArrivalDevice)
                .Include(s => s.DepartureDevice)
                .Where(s => s.UserId == id
            && ((s.Arrival.Value.Date >= from.Date && s.Departure == null && s.Arrival.Value.Date <= to.Date)
            || (s.Arrival.Value.Date >= from.Date && s.Departure.Value.Date <= to.Date)
            || (s.Departure.Value.Date <= to.Date && s.Arrival == null && s.Departure.Value.Date >= from.Date)))
                .ToListAsync();
            ViewBag.From = from.Date;
            ViewBag.To = to.Date;
            return View(new PageUniversalModel<IEnumerable<Shift>>(shifts));

        }

        [HttpPost]
        [Route("Employee/Shifts/Update")]
        public async Task<IActionResult> EmployeeShiftUpdate(Shift shift) {
            if (shift == null) {
                return BadRequest(new ApiDtoOut.Response("Wrong format", 400));
            }
            if (await _globalContext.Shifts.AnyAsync(s => s.Id == shift.Id)) {
                _globalContext.Shifts.Update(shift);
                await _globalContext.SaveChangesAsync();
                return Ok(new ApiDtoOut.Response("Shift updated successfully"));
            }
            return BadRequest(new ApiDtoOut.Response("Shift does not exist", 400));
        }

            [HttpPost]
        [Route("Employee/Shifts/UpdateTime")]
        public async Task<IActionResult> EmployeeShiftUpdateTime(ShiftDtoIn.TimeUpdate shift) {
            if (!shift.Time.HasValue) {
                return BadRequest(new ApiDtoOut.Response("Wrong format", 400));
            }
            Shift shiftToUpdate = await _globalContext.Shifts.SingleOrDefaultAsync(s => s.Id == shift.Id);
            if (shiftToUpdate != default) {
                if(shift.Type == "arrival") {
                    if(shiftToUpdate.Arrival == null) {
                        shiftToUpdate.Arrival = shiftToUpdate.Departure;
                    }
                    shiftToUpdate.Arrival = shiftToUpdate.Arrival.Value.Date.Add(shift.Time.Value);
                    shiftToUpdate.Arrival = TimeZoneInfo.ConvertTimeToUtc(shiftToUpdate.Arrival.Value, TimeZoneInfo.Local);
                    shiftToUpdate.SensorArrivalId = null;
                } else {
                    if (shiftToUpdate.Departure == null) {
                        shiftToUpdate.Departure = shiftToUpdate.Arrival;
                    }
                    shiftToUpdate.Departure = shiftToUpdate.Departure.Value.Date.Add(shift.Time.Value);
                    shiftToUpdate.Departure = TimeZoneInfo.ConvertTimeToUtc(shiftToUpdate.Departure.Value, TimeZoneInfo.Local);
                    shiftToUpdate.SensorDepartureId = null;
                }
                _globalContext.Shifts.Update(shiftToUpdate);
                await _globalContext.SaveChangesAsync();
                return Ok(new ApiDtoOut.Response("Shift updated successfully"));
            }
            return BadRequest(new ApiDtoOut.Response("Shift does not exist", 400));
        }

        [HttpGet]
        [Route("Employee/List")]
        public async Task<IActionResult> EmployeeList() {
            IEnumerable<User> users = await _globalContext.Users
                .Include(u => u.Role)
                .ToListAsync();
            return View(new PageUniversalModel<IEnumerable<User>>(users));
        }

        [HttpGet]
        [Route("Employee/Edit/{id}")]
        [Route("Employee/Add")]
        public async Task<IActionResult> EmployeeAddEdit(int id = 0) {
            ViewBag.Roles = new SelectList(await _globalContext.Roles.ToListAsync(), "Id", "RoleName");
            User? user = new();
            if(id != 0) {
                user = await _globalContext.Users.SingleOrDefaultAsync(u => u.Id == id);
                if(user == default) {
                    user = null;
                }
            }
            return View(new PageUniversalModel<User>(user));
        }
        [HttpPost]
        [Route("Employee/Edit/{id}")]
        [Route("Employee/Add")]
        public async Task<IActionResult> EmployeeSave(PageUniversalModel<User> userDtoIn) {
            User user = userDtoIn.Data;
            ViewBag.Roles = new SelectList(await _globalContext.Roles.ToListAsync(), "Id", "RoleName");
            if (ModelState.IsValid) {
                bool passwordChanged = false;
                User? originalUser = await _globalContext.Users
                    .AsNoTracking()
                    .SingleOrDefaultAsync(u => u.Id == user.Id);
                if (user.Password != null) {
                    passwordChanged = true;
                    user.SetPassword(user.Password);
                }
                if (originalUser == default) {
                    await _globalContext.Users.AddAsync(user);
                } else {
                    if(!passwordChanged) {
                        user.PasswordHash = originalUser.PasswordHash;
                    }
                    _globalContext.Users.Update(user);
                }
                await _globalContext.SaveChangesAsync();
                return RedirectToAction("EmployeeList");
            }
            PageUniversalModel<User> model = new PageUniversalModel<User>(user);
            model.Message = model.GetStringFromValidation(ModelState.Values);
            return View("EmployeeAddEdit", model);
        }

        [HttpPost]
        [Route("Employee/Delete")]
        public async Task<IActionResult> EmployeeDelete(int id) {
            if(id == 0) {
                User? user = await _globalContext.Users
                    .Include(u => u.AccessDevices)
                    .Include(u => u.Shifts)
                    .SingleOrDefaultAsync(u => u.Id == id);
                if(user != default) {
                    user.Shifts.Clear();
                    user.AccessDevices.Clear();
                    _globalContext.Users.Update(user);
                    _globalContext.Users.Remove(user);
                    await _globalContext.SaveChangesAsync();
                    return Ok();
                }
            }
            return BadRequest();
        }

        [HttpGet]
        [Route("Employee/Detail/{id}")]
        public async Task<IActionResult> EmployeeDetail(int id = 0) {
            User? u = await _globalContext.Users
                .Include(u => u.AccessDevices)
                .Include(u => u.Role)
                .SingleOrDefaultAsync(u => u.Id == id);
            if(u == default) {
                return RedirectToAction("EmployeeList");
            }
            ViewBag.AccessDevices = u.AccessDevices;
            return View(new PageUniversalModel<User>(u));
        }
        #endregion

        #region AccessDevices
        [HttpPost]
        [Route("AccessDevice/Save")]
        public async Task<IActionResult> SaveAccessDevice(AccessDevice accessDevice) {
            try {
                if (accessDevice == null) {
                    return BadRequest(new ApiDtoOut.Response("Chyba", 400));
                }
                if (accessDevice.Id == 0) {
                    await _globalContext.AccessDevices.AddAsync(accessDevice);
                } else {
                    _globalContext.AccessDevices.Update(accessDevice);
                }
                await _globalContext.SaveChangesAsync();
                _logger.LogInformation($"AccessDevice with id {accessDevice.Id} was updated/created");
                return Ok(new ApiDtoOut.Response("Uloženo"));
            } catch (Exception ex) {
                _logger.LogError(ex, "SaveDeviceError: ");
                return StatusCode(500);
            }
        }
        [HttpPost]
        [Route("AccessDevice/Remove")]
        public async Task<IActionResult> RemoveAccessDevice(int id) {
            AccessDevice? device = await _globalContext.AccessDevices.SingleOrDefaultAsync(ad => ad.Id == id);
            if (device == default) {
                return BadRequest();
            }
            _globalContext.AccessDevices.Remove(device);
            await _globalContext.SaveChangesAsync();
            return Ok();
        }
        #endregion

        #region Roles
        [HttpGet]
        [Route("Role/Manage")]
        public async Task<IActionResult> RoleManagement() {
            ViewBag.RolesToSkip = AppHelper.GetAdminIdRoleList();
            IEnumerable<Role> roles = await _globalContext.Roles.ToListAsync();
            return View(new PageUniversalModel<IEnumerable<Role>>(roles));
        }

        [HttpPost]
        [Route("Role/Save")]
        public async Task<IActionResult> RoleSave(Role role) {
            if (role != null) {

Backend/Controllers/DashboardController.cs
using BP_AttendanceSystem_Lepine.Models;
using BP_AttendanceSystem_Lepine.Models.Db;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Security.Claims;

namespace BP_AttendanceSystem_Lepine.Controllers {
    [Authorize]
    public class DashboardController : Controller {
        private readonly ILogger<DashboardController> _logger;
        private GlobalContext _globalContext;

        public DashboardController(ILogger<DashboardController> logger, GlobalContext gc) {
            _logger = logger;
            _globalContext = gc;
        }

        public IActionResult Index() {
            return RedirectToAction("MyShifts");
        }
        [HttpGet]
        [Route("MyShifts")]
        public async Task<IActionResult> MyShifts(DateTime month = default) {
            if(month == default) {
                month = DateTime.Now;
            }
            DateTime from = new(month.Year, month.Month, 1);
            DateTime to = from.AddMonths(1).AddDays(-1);
            ViewBag.Month = month;
            int id = int.Parse(User.Claims.FirstOrDefault(u => u.Type == ClaimTypes.Sid).Value);
            IEnumerable<Shift> shifts = await _globalContext.Shifts
                .Include(s => s.User)
                .Include(s => s.ArrivalDevice)
                .Include(s => s.DepartureDevice)
                .Where(s => s.UserId == id
            && ((s.Arrival.Value.Date >= from.Date && s.Departure == null && s.Arrival.Value.Date <= to.Date)
            || (s.Arrival.Value.Date >= from.Date && s.Departure.Value.Date <= to.Date)
            || (s.Departure.Value.Date <= to.Date && s.Arrival == null && s.Departure.Value.Date >= from.Date)))
                .ToListAsync();

            return View(new PageUniversalModel<IEnumerable<Shift>>(shifts));
        }

        [HttpGet]
        [Route("Error")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Backend/Views/Shared/_AccessDeviceAssignmentPartial.cshtml
@model int

<table class="table table-striped mt-4">
    <thead>
        <tr>
            <td colspan="3">
            <a class="btn btn-outline-success" href="#" onclick="openModal(null)">Přidat přístupové zařízení</a>
            </td>
        </tr>
        <tr>
            <th>Typ</th>
            <th>Popis</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (BP_AttendanceSystem_Lepine.Models.Db.AccessDevice item in ViewBag.AccessDevices) {
            <tr>
                <td>
                    @item.GetAccessType()
                </td>
                <td>@item.Description</td>
                <td style="text-align: right">
                    <a class="btn btn-outline-secondary" href="#" onclick="openModal({fingerprint: '@item.FingerprintData', desc: '@item.Description', id: @item.Id, chipId: '@item.ChipId'})">Upravit</a>
                    <a class="btn btn-outline-danger" href="#" onclick="removeDevice(@item.Id)">Odstranit</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<div class="modal fade" id="addEditADModal" tabindex="-1" aria-labelledby="addEditADModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addEditADModalLabel">--NAME--</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" id="id" value="" />
                    <div class="mb-3">
                        <label for="desc" class="col-form-label">Popis</label>
                        <input type="text" class="form-control" id="desc">
                    </div>
                    <div class="mb-3">
                        <label for="chipId" class="col-form-label">Čip</label>
                        <input type="text" class="form-control" id="chipId">
                    </div>
                    nebo
                    <div class="mb-3">
                        <label for="fingerprint" class="col-form-label">Data otisku</label>
                        <input type="text" class="form-control" id="fingerprint">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Zavřít</button>
                <button type="button" class="btn btn-primary" onclick="saveDevice()">Uložit</button>
            </div>
        </div>
    </div>
</div>
@Html.PartialSectionScripts(
    @<script>
             let myModal = new bootstrap.Modal(document.getElementById('addEditADModal'));
             function openModal(obj) {
                 if (obj === null) {
                     $("#addEditADModalLabel").text("Přidat zařízení");
                 } else {
                     $("#desc").val(obj.desc);
                     $("#fingerprint").val(obj.fingerprint);
                     $("#id").val(obj.id);
                     $("#chipId").val(obj.chipId);
                     $("#addEditADModalLabel").text("Upravit zařízení");
                 }
                 myModal.show();
             }
             function saveDevice() {
                 $.post("/Admin/AccessDevice/Save", {
                     description: $("#desc").val(),
                     userId: @Model,
                     fingerprintId: $("#fingerprint").val(),
                     id: $("#id").val(),
                     chipId: $("#chipId").val()
                 }).then(res => {
                     location.reload();
                     //myModal.hide();
                 }).fail(err => {
                     console.error(err);
                 });
             }
             function removeDevice(id) {
                 $.post("/Admin/AccessDevice/Remove", {
                     id
                 }).then(res => {
                     location.reload();
                 });
             }
    </script>
)

Backend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - AttendanceSystem Lepine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BP_AttendanceSystem_Lepine.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Docházkový systém</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Můj přehled</a>
                        </li>
                        @{
                            if (User.IsInRole("0")) {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="EmployeeList">Seznam zaměstnanců</a>
                                </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="DeviceManagement">Správa zařízení</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="RoleManagement">Správa rolí</a>
                            </li>
                            }
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a href="/Auth/Logout" class="nav-link text-dark">Odhlásit se <i class="fas fa-sign-out-alt"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BP_AttendanceSystem_Lepine
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @Html.RenderPartialSectionScripts()
</body>
</html>